##
# Model to save tokens generated by firebase and use it for push notification on the dashboard
# this token will be associated with the browser admin session {Admin::Token Admin::Token}
# ## Table's Columns
# - value => [string] It stores firebase token
# - created_at => [datetime]
# - updated_at => [datetime]
class Admin::PushNotificationToken < ApplicationRecord
  include PushNotificationAction

  self.table_name = 'admin_push_notification_tokens'

  has_one :admin_token, class_name: 'Admin::Token', foreign_key: 'admin_push_notification_token_id'
end
