##
# Model to save tokens generated by firebase and use it for push notification on the dashboard
# this token will be associated with the browser user session {User::Token User::Token}
# ## Table's Columns
# - value => [string] It stores firebase token
# - created_at => [datetime]
# - updated_at => [datetime]
class User::PushNotificationToken < ApplicationRecord
  include PushNotificationAction

  self.table_name = 'user_push_notification_tokens'

  has_one :user_token, class_name: 'User::Token', foreign_key: 'user_push_notification_token_id'

end
