##
# Model to store violation generated by a {ParkingSession parking session}. This is created on violation_commited.rb
# ## Table's Columns
# - description => [string] It's not used, we instead use the description associated to {Parking::Rule parking rule} instance
# - fixed_at => [datetime] **Unknown reason**
# - rule_id => [bigint] Reference ID to a {Parking::Rule parking rule}
# - session_id => [bigint] Reference ID to a {ParkingSession parking session}
# - parking_vehicle_rules_id => [bigint] Reference ID to a {Parking::VehicleRule parking vehicle rule}
# - created_at => [datetime]
# - updated_at => [datetime]
class Parking::Violation < ApplicationRecord
  belongs_to :rule
  belongs_to :vehicle_rule, class_name: "Parking::VehicleRule", foreign_key: :parking_vehicle_rules_id
  belongs_to :session, class_name: 'ParkingSession'

  with_options dependent: :destroy do |assoc|
    assoc.has_many :images, as: :imageable
    assoc.has_one :ticket
  end
end
